from .accountSerializer import AccountSerializer
from .userSerializer import UserSerializer
from .familiarSerializer import familiarSerializer
from .pacienteSerializer import pacienteSerializer
from .personal_medicoSerializer import personal_medicoSerializer
from .signos_vitalesSerializer import signos_vitalesSerializer
from .historia_clinicaSerializer import historia_clinicaSerializer
